package com.keyboard.utils;

import com.keyboard.bean.EmoticonBean;

public class DefEmoticons {
    /**
     * emoji
     */
    public static final String[] emojiArray = {
            // PEOPLE
            "emoji_0x1f604" + ".png," + EmoticonBean.fromCodePoint(0x1f604),
            "emoji_0x1f603" + ".png," + EmoticonBean.fromCodePoint(0x1f603),
//            EmojiBean.fromCodePoint(0x1f600),
            "emoji_0x1f60a" + ".png," + EmoticonBean.fromCodePoint(0x1f60a),
//            EmojiBean.fromChar((char) 0x263a),
            "emoji_0x1f609" + ".png," + EmoticonBean.fromCodePoint(0x1f609),
            "emoji_0x1f60d" + ".png," + EmoticonBean.fromCodePoint(0x1f60d),
            "emoji_0x1f618" + ".png," + EmoticonBean.fromCodePoint(0x1f618),
            "emoji_0x1f61a" + ".png," + EmoticonBean.fromCodePoint(0x1f61a),
//            EmojiBean.fromCodePoint(0x1f617),
//            EmojiBean.fromCodePoint(0x1f619),
            "emoji_0x1f61c" + ".png," + EmoticonBean.fromCodePoint(0x1f61c),
            "emoji_0x1f61d" + ".png," + EmoticonBean.fromCodePoint(0x1f61d),
//            EmojiBean.fromCodePoint(0x1f61b),
            "emoji_0x1f633" + ".png," + EmoticonBean.fromCodePoint(0x1f633),
            "emoji_0x1f601" + ".png," + EmoticonBean.fromCodePoint(0x1f601),
            "emoji_0x1f614" + ".png," + EmoticonBean.fromCodePoint(0x1f614),
            "emoji_0x1f60c" + ".png," + EmoticonBean.fromCodePoint(0x1f60c),
            "emoji_0x1f612" + ".png," + EmoticonBean.fromCodePoint(0x1f612),
            "emoji_0x1f61e" + ".png," + EmoticonBean.fromCodePoint(0x1f61e),
            "emoji_0x1f623" + ".png," + EmoticonBean.fromCodePoint(0x1f623),
            "emoji_0x1f622" + ".png," + EmoticonBean.fromCodePoint(0x1f622),
            "emoji_0x1f602" + ".png," + EmoticonBean.fromCodePoint(0x1f602),
            "emoji_0x1f62d" + ".png," + EmoticonBean.fromCodePoint(0x1f62d),
            "emoji_0x1f62a" + ".png," + EmoticonBean.fromCodePoint(0x1f62a),
            "emoji_0x1f625" + ".png," + EmoticonBean.fromCodePoint(0x1f625),
            "emoji_0x1f630" + ".png," + EmoticonBean.fromCodePoint(0x1f630),
//            EmojiBean.fromCodePoint(0x1f605),
            "emoji_0x1f613" + ".png," + EmoticonBean.fromCodePoint(0x1f613),
//            EmojiBean.fromCodePoint(0x1f629),
//            EmojiBean.fromCodePoint(0x1f62b),
            "emoji_0x1f628" + ".png," + EmoticonBean.fromCodePoint(0x1f628),
            "emoji_0x1f631" + ".png," + EmoticonBean.fromCodePoint(0x1f631),
            "emoji_0x1f620" + ".png," + EmoticonBean.fromCodePoint(0x1f620),
            "emoji_0x1f621" + ".png," + EmoticonBean.fromCodePoint(0x1f621),
//            EmojiBean.fromCodePoint(0x1f624),
            "emoji_0x1f616" + ".png," + EmoticonBean.fromCodePoint(0x1f616),
//            EmojiBean.fromCodePoint(0x1f606),
//            EmojiBean.fromCodePoint(0x1f60b),
            "emoji_0x1f637" + ".png," + EmoticonBean.fromCodePoint(0x1f637),
//            EmojiBean.fromCodePoint(0x1f60e),
//            EmojiBean.fromCodePoint(0x1f634),
//            EmojiBean.fromCodePoint(0x1f635),
            "emoji_0x1f632" + ".png," + EmoticonBean.fromCodePoint(0x1f632),
//            EmojiBean.fromCodePoint(0x1f61f),
//            EmojiBean.fromCodePoint(0x1f626),
//            EmojiBean.fromCodePoint(0x1f627),
//            EmojiBean.fromCodePoint(0x1f608),
            "emoji_0x1f47f.png," + EmoticonBean.fromCodePoint(0x1f47f),
//            EmojiBean.fromCodePoint(0x1f62e),
//            EmojiBean.fromCodePoint(0x1f62c),
//            EmojiBean.fromCodePoint(0x1f610),
//            EmojiBean.fromCodePoint(0x1f615),
//            EmojiBean.fromCodePoint(0x1f62f),
//            EmojiBean.fromCodePoint(0x1f636),
//            EmojiBean.fromCodePoint(0x1f607),
            "emoji_0x1f60f" + ".png," + EmoticonBean.fromCodePoint(0x1f60f),
//            EmojiBean.fromCodePoint(0x1f611),
//            EmojiBean.fromCodePoint(0x1f472),
//            EmojiBean.fromCodePoint(0x1f473),
//            EmojiBean.fromCodePoint(0x1f46e),
//            EmojiBean.fromCodePoint(0x1f477),
//            EmojiBean.fromCodePoint(0x1f482),
//            EmojiBean.fromCodePoint(0x1f476),
            "emoji_0x1f466" + ".png," + EmoticonBean.fromCodePoint(0x1f466),
            "emoji_0x1f467" + ".png," + EmoticonBean.fromCodePoint(0x1f467),
            "emoji_0x1f468" + ".png," + EmoticonBean.fromCodePoint(0x1f468),
            "emoji_0x1f469" + ".png," + EmoticonBean.fromCodePoint(0x1f469),
//            EmojiBean.fromCodePoint(0x1f474),
//            EmojiBean.fromCodePoint(0x1f475),
//            EmojiBean.fromCodePoint(0x1f471),
//            EmojiBean.fromCodePoint(0x1f47c),
//            EmojiBean.fromCodePoint(0x1f478),
//            EmojiBean.fromCodePoint(0x1f63a),
//            EmojiBean.fromCodePoint(0x1f638),
//            EmojiBean.fromCodePoint(0x1f63b),
//            EmojiBean.fromCodePoint(0x1f63d),
//            EmojiBean.fromCodePoint(0x1f63c),
//            EmojiBean.fromCodePoint(0x1f640),
//            EmojiBean.fromCodePoint(0x1f63f),
//            EmojiBean.fromCodePoint(0x1f639),
//            EmojiBean.fromCodePoint(0x1f63e),
//            EmojiBean.fromCodePoint(0x1f479),
//            EmojiBean.fromCodePoint(0x1f47a),
//            EmojiBean.fromCodePoint(0x1f648),
//            EmojiBean.fromCodePoint(0x1f649),
//            EmojiBean.fromCodePoint(0x1f64a),
//            EmojiBean.fromCodePoint(0x1f480),
//            EmojiBean.fromCodePoint(0x1f47d),
//            EmojiBean.fromCodePoint(0x1f4a9),
//            EmojiBean.fromCodePoint(0x1f525),
//            EmojiBean.fromChar((char) 0x2728),
            "emoji_0x1f31f.png," + EmoticonBean.fromCodePoint(0x1f31f),
//            EmojiBean.fromCodePoint(0x1f4ab),
//            EmojiBean.fromCodePoint(0x1f4a5),
//            EmojiBean.fromCodePoint(0x1f4a2),
//            EmojiBean.fromCodePoint(0x1f4a6),
//            EmojiBean.fromCodePoint(0x1f4a7),
//            EmojiBean.fromCodePoint(0x1f4a4),
//            EmojiBean.fromCodePoint(0x1f4a8),
//            EmojiBean.fromCodePoint(0x1f442),
//            EmojiBean.fromCodePoint(0x1f440),
//            EmojiBean.fromCodePoint(0x1f443),
//            EmojiBean.fromCodePoint(0x1f445),
            "emoji_0x1f444" + ".png," + EmoticonBean.fromCodePoint(0x1f444),
            "emoji_0x1f44d.png," + EmoticonBean.fromCodePoint(0x1f44d),
            "emoji_0x1f44e.png," + EmoticonBean.fromCodePoint(0x1f44e),
            "emoji_0x1f44c.png," + EmoticonBean.fromCodePoint(0x1f44c),
            "emoji_0x1f44a.png," + EmoticonBean.fromCodePoint(0x1f44a),
            "emoji_0x270a" + ".png," + EmoticonBean.fromChar((char) 0x270a),
            "emoji_0x270c" + ".png," + EmoticonBean.fromChar((char) 0x270c),
//            EmojiBean.fromCodePoint(0x1f44b),
//            EmojiBean.fromChar((char) 0x270b),
//            EmojiBean.fromCodePoint(0x1f450),
            "emoji_0x1f446" + ".png," + EmoticonBean.fromCodePoint(0x1f446),
            "emoji_0x1f447" + ".png," + EmoticonBean.fromCodePoint(0x1f447),
            "emoji_0x1f449" + ".png," + EmoticonBean.fromCodePoint(0x1f449),
            "emoji_0x1f448" + ".png," + EmoticonBean.fromCodePoint(0x1f448),
//            EmojiBean.fromCodePoint(0x1f64c),
            "emoji_0x1f64f" + ".png," + EmoticonBean.fromCodePoint(0x1f64f),
//            EmojiBean.fromChar((char) 0x261d),
            "emoji_0x1f44f.png," + EmoticonBean.fromCodePoint(0x1f44f),
            "emoji_0x1f4aa.png," + EmoticonBean.fromCodePoint(0x1f4aa),
//            EmojiBean.fromCodePoint(0x1f6b6),
//            EmojiBean.fromCodePoint(0x1f3c3),
//            EmojiBean.fromCodePoint(0x1f483),
//            EmojiBean.fromCodePoint(0x1f46b),
//            EmojiBean.fromCodePoint(0x1f46a),
//            EmojiBean.fromCodePoint(0x1f46c),
//            EmojiBean.fromCodePoint(0x1f46d),
//            EmojiBean.fromCodePoint(0x1f48f),
//            EmojiBean.fromCodePoint(0x1f491),
//            EmojiBean.fromCodePoint(0x1f46f),
//            EmojiBean.fromCodePoint(0x1f646),
//            EmojiBean.fromCodePoint(0x1f645),
//            EmojiBean.fromCodePoint(0x1f481),
//            EmojiBean.fromCodePoint(0x1f64b),
//            EmojiBean.fromCodePoint(0x1f486),
//            EmojiBean.fromCodePoint(0x1f487),
//            EmojiBean.fromCodePoint(0x1f485),
//            EmojiBean.fromCodePoint(0x1f470),
//            EmojiBean.fromCodePoint(0x1f64e),
//            EmojiBean.fromCodePoint(0x1f64d),
//            EmojiBean.fromCodePoint(0x1f647),
//            EmojiBean.fromCodePoint(0x1f3a9),
//            EmojiBean.fromCodePoint(0x1f451),
//            EmojiBean.fromCodePoint(0x1f452),
//            EmojiBean.fromCodePoint(0x1f45f),
//            EmojiBean.fromCodePoint(0x1f45e),
//            EmojiBean.fromCodePoint(0x1f461),
//            EmojiBean.fromCodePoint(0x1f460),
//            EmojiBean.fromCodePoint(0x1f462),
//            EmojiBean.fromCodePoint(0x1f455),
//            EmojiBean.fromCodePoint(0x1f454),
//            EmojiBean.fromCodePoint(0x1f45a),
            "emoji_0x1f457" + ".png," + EmoticonBean.fromCodePoint(0x1f457),
//            EmojiBean.fromCodePoint(0x1f3bd),
//            EmojiBean.fromCodePoint(0x1f456),
//            EmojiBean.fromCodePoint(0x1f458),
//            EmojiBean.fromCodePoint(0x1f459),
//            EmojiBean.fromCodePoint(0x1f4bc),
//            EmojiBean.fromCodePoint(0x1f45c),
//            EmojiBean.fromCodePoint(0x1f45d),
//            EmojiBean.fromCodePoint(0x1f45b),
//            EmojiBean.fromCodePoint(0x1f453),
            "emoji_0x1f380" + ".png," + EmoticonBean.fromCodePoint(0x1f380),
//            EmojiBean.fromCodePoint(0x1f302),
//            EmojiBean.fromCodePoint(0x1f484),
//            EmojiBean.fromCodePoint(0x1f49b),
//            EmojiBean.fromCodePoint(0x1f499),
//            EmojiBean.fromCodePoint(0x1f49c),
//            EmojiBean.fromCodePoint(0x1f49a),
            "emoji_0x2764" + ".png," + EmoticonBean.fromChar((char) 0x2764),
            "emoji_0x1f494" + ".png," + EmoticonBean.fromCodePoint(0x1f494),
//            EmojiBean.fromCodePoint(0x1f497),
//            EmojiBean.fromCodePoint(0x1f493),
//            EmojiBean.fromCodePoint(0x1f495),
//            EmojiBean.fromCodePoint(0x1f496),
//            EmojiBean.fromCodePoint(0x1f49e),
//            EmojiBean.fromCodePoint(0x1f498),
//            EmojiBean.fromCodePoint(0x1f48c),
//            EmojiBean.fromCodePoint(0x1f48b),
//            EmojiBean.fromCodePoint(0x1f48d),
            "emoji_0x1f48e.png," + EmoticonBean.fromCodePoint(0x1f48e),
//            EmojiBean.fromCodePoint(0x1f464),
//            EmojiBean.fromCodePoint(0x1f465),
//            EmojiBean.fromCodePoint(0x1f4ac),
//            EmojiBean.fromCodePoint(0x1f463),
//            EmojiBean.fromCodePoint(0x1f4ad),

            // NATURE
            "emoji_0x1f436" + ".png," + EmoticonBean.fromCodePoint(0x1f436),
//            EmojiBean.fromCodePoint(0x1f43a),
            "emoji_0x1f431" + ".png," + EmoticonBean.fromCodePoint(0x1f431),
//            EmojiBean.fromCodePoint(0x1f42d),
//            EmojiBean.fromCodePoint(0x1f439),
//            EmojiBean.fromCodePoint(0x1f430),
//            EmojiBean.fromCodePoint(0x1f438),
//            EmojiBean.fromCodePoint(0x1f42f),
//            EmojiBean.fromCodePoint(0x1f428),
//            EmojiBean.fromCodePoint(0x1f43b),
//            EmojiBean.fromCodePoint(0x1f437),
//            EmojiBean.fromCodePoint(0x1f43d),
//            EmojiBean.fromCodePoint(0x1f42e),
//            EmojiBean.fromCodePoint(0x1f417),
//            EmojiBean.fromCodePoint(0x1f435),
//            EmojiBean.fromCodePoint(0x1f412),
//            EmojiBean.fromCodePoint(0x1f434),
//            EmojiBean.fromCodePoint(0x1f411),
//            EmojiBean.fromCodePoint(0x1f418),
//            EmojiBean.fromCodePoint(0x1f43c),
//            EmojiBean.fromCodePoint(0x1f427),
//            EmojiBean.fromCodePoint(0x1f426),
//            EmojiBean.fromCodePoint(0x1f424),
//            EmojiBean.fromCodePoint(0x1f425),
//            EmojiBean.fromCodePoint(0x1f423),
//            EmojiBean.fromCodePoint(0x1f414),
//            EmojiBean.fromCodePoint(0x1f40d),
//            EmojiBean.fromCodePoint(0x1f422),
//            EmojiBean.fromCodePoint(0x1f41b),
//            EmojiBean.fromCodePoint(0x1f41d),
//            EmojiBean.fromCodePoint(0x1f41c),
//            EmojiBean.fromCodePoint(0x1f41e),
//            EmojiBean.fromCodePoint(0x1f40c),
//            EmojiBean.fromCodePoint(0x1f419),
//            EmojiBean.fromCodePoint(0x1f41a),
//            EmojiBean.fromCodePoint(0x1f420),
//            EmojiBean.fromCodePoint(0x1f41f),
//            EmojiBean.fromCodePoint(0x1f42c),
//            EmojiBean.fromCodePoint(0x1f433),
//            EmojiBean.fromCodePoint(0x1f40b),
//            EmojiBean.fromCodePoint(0x1f404),
//            EmojiBean.fromCodePoint(0x1f40f),
//            EmojiBean.fromCodePoint(0x1f400),
//            EmojiBean.fromCodePoint(0x1f403),
//            EmojiBean.fromCodePoint(0x1f405),
//            EmojiBean.fromCodePoint(0x1f407),
//            EmojiBean.fromCodePoint(0x1f409),
//            EmojiBean.fromCodePoint(0x1f40e),
//            EmojiBean.fromCodePoint(0x1f410),
//            EmojiBean.fromCodePoint(0x1f413),
//            EmojiBean.fromCodePoint(0x1f415),
//            EmojiBean.fromCodePoint(0x1f416),
//            EmojiBean.fromCodePoint(0x1f401),
//            EmojiBean.fromCodePoint(0x1f402),
//            EmojiBean.fromCodePoint(0x1f432),
//            EmojiBean.fromCodePoint(0x1f421),
//            EmojiBean.fromCodePoint(0x1f40a),
//            EmojiBean.fromCodePoint(0x1f42b),
//            EmojiBean.fromCodePoint(0x1f42a),
//            EmojiBean.fromCodePoint(0x1f406),
//            EmojiBean.fromCodePoint(0x1f408),
//            EmojiBean.fromCodePoint(0x1f429),
//            EmojiBean.fromCodePoint(0x1f43e),
//            EmojiBean.fromCodePoint(0x1f490),
//            EmojiBean.fromCodePoint(0x1f338),
//            EmojiBean.fromCodePoint(0x1f337),
//            EmojiBean.fromCodePoint(0x1f340),
            "emoji_0x1f339" + ".png," + EmoticonBean.fromCodePoint(0x1f339),
            "emoji_0x1f33b.png" + EmoticonBean.fromCodePoint(0x1f33b),
//            EmojiBean.fromCodePoint(0x1f33a),
            "emoji_0x1f341" + ".png," + EmoticonBean.fromCodePoint(0x1f341),
            "emoji_0x1f343" + ".png," + EmoticonBean.fromCodePoint(0x1f343),
//            EmojiBean.fromCodePoint(0x1f342),
//            EmojiBean.fromCodePoint(0x1f33f),
//            EmojiBean.fromCodePoint(0x1f33e),
//            EmojiBean.fromCodePoint(0x1f344),
//            EmojiBean.fromCodePoint(0x1f335),
//            EmojiBean.fromCodePoint(0x1f334),
//            EmojiBean.fromCodePoint(0x1f332),
//            EmojiBean.fromCodePoint(0x1f333),
//            EmojiBean.fromCodePoint(0x1f330),
//            EmojiBean.fromCodePoint(0x1f331),
//            EmojiBean.fromCodePoint(0x1f33c),
//            EmojiBean.fromCodePoint(0x1f310),
//            EmojiBean.fromCodePoint(0x1f31e),
//            EmojiBean.fromCodePoint(0x1f31d),
//            EmojiBean.fromCodePoint(0x1f31a),
//            EmojiBean.fromCodePoint(0x1f311),
//            EmojiBean.fromCodePoint(0x1f312),
//            EmojiBean.fromCodePoint(0x1f313),
//            EmojiBean.fromCodePoint(0x1f314),
//            EmojiBean.fromCodePoint(0x1f315),
//            EmojiBean.fromCodePoint(0x1f316),
//            EmojiBean.fromCodePoint(0x1f317),
//            EmojiBean.fromCodePoint(0x1f318),
//            EmojiBean.fromCodePoint(0x1f31c),
//            EmojiBean.fromCodePoint(0x1f31b),
            "emoji_0x1f319" + ".png," + EmoticonBean.fromCodePoint(0x1f319),
//            EmojiBean.fromCodePoint(0x1f30d),
//            EmojiBean.fromCodePoint(0x1f30e),
//            EmojiBean.fromCodePoint(0x1f30f),
//            EmojiBean.fromCodePoint(0x1f30b),
//            EmojiBean.fromCodePoint(0x1f30c),
//            EmojiBean.fromCodePoint(0x1f320),
//            EmojiBean.fromChar((char) 0x2b50),
            "emoji_0x2600" + ".png," + EmoticonBean.fromChar((char) 0x2600),
//            EmojiBean.fromChar((char) 0x26c5),
            "emoji_0x2601" + ".png," + EmoticonBean.fromChar((char) 0x2601),
            "emoji_0x26a1" + ".png," + EmoticonBean.fromChar((char) 0x26a1),
            "emoji_0x2614" + ".png," + EmoticonBean.fromChar((char) 0x2614),
//            EmojiBean.fromChar((char) 0x2744),
//            EmojiBean.fromChar((char) 0x26c4),
//            EmojiBean.fromCodePoint(0x1f300),
//            EmojiBean.fromCodePoint(0x1f301),
//            EmojiBean.fromCodePoint(0x1f308),
//            EmojiBean.fromCodePoint(0x1f30a),

            // object
//            EmojiBean.fromCodePoint(0x1f38d),
//            EmojiBean.fromCodePoint(0x1f49d),
//            EmojiBean.fromCodePoint(0x1f38e),
//            EmojiBean.fromCodePoint(0x1f392),
//            EmojiBean.fromCodePoint(0x1f393),
//            EmojiBean.fromCodePoint(0x1f38f),
//            EmojiBean.fromCodePoint(0x1f386),
//            EmojiBean.fromCodePoint(0x1f387),
//            EmojiBean.fromCodePoint(0x1f390),
//            EmojiBean.fromCodePoint(0x1f391),
//            EmojiBean.fromCodePoint(0x1f383),
            "emoji_0x1f47b" + ".png," + EmoticonBean.fromCodePoint(0x1f47b),
            "emoji_0x1f385" + ".png," + EmoticonBean.fromCodePoint(0x1f385),
//            EmojiBean.fromCodePoint(0x1f384),
            "emoji_0x1f381" + ".png," + EmoticonBean.fromCodePoint(0x1f381),
//            EmojiBean.fromCodePoint(0x1f38b),
//            EmojiBean.fromCodePoint(0x1f389),
//            EmojiBean.fromCodePoint(0x1f38a),
//            EmojiBean.fromCodePoint(0x1f388),
//            EmojiBean.fromCodePoint(0x1f38c),
//            EmojiBean.fromCodePoint(0x1f52e),
//            EmojiBean.fromCodePoint(0x1f3a5),
//            EmojiBean.fromCodePoint(0x1f4f7),
//            EmojiBean.fromCodePoint(0x1f4f9),
//            EmojiBean.fromCodePoint(0x1f4fc),
//            EmojiBean.fromCodePoint(0x1f4bf),
//            EmojiBean.fromCodePoint(0x1f4c0),
//            EmojiBean.fromCodePoint(0x1f4bd),
//            EmojiBean.fromCodePoint(0x1f4be),
//            EmojiBean.fromCodePoint(0x1f4bb),
            "emoji_0x1f4f1" + ".png," + EmoticonBean.fromCodePoint(0x1f4f1),
//            EmojiBean.fromChar((char) 0x260e),
//            EmojiBean.fromCodePoint(0x1f4de),
//            EmojiBean.fromCodePoint(0x1f4df),
//            EmojiBean.fromCodePoint(0x1f4e0),
//            EmojiBean.fromCodePoint(0x1f4e1),
//            EmojiBean.fromCodePoint(0x1f4fa),
//            EmojiBean.fromCodePoint(0x1f4fb),
//            EmojiBean.fromCodePoint(0x1f508),
//            EmojiBean.fromCodePoint(0x1f509),
//            EmojiBean.fromCodePoint(0x1f50a),
//            EmojiBean.fromCodePoint(0x1f507),
//            EmojiBean.fromCodePoint(0x1f514),
//            EmojiBean.fromCodePoint(0x1f515),
//            EmojiBean.fromCodePoint(0x1f4e2),
//            EmojiBean.fromCodePoint(0x1f4e3),
//            EmojiBean.fromChar((char) 0x23f3),
//            EmojiBean.fromChar((char) 0x231b),
//            EmojiBean.fromChar((char) 0x23f0),
//            EmojiBean.fromChar((char) 0x231a),
//            EmojiBean.fromCodePoint(0x1f513),
//            EmojiBean.fromCodePoint(0x1f512),
//            EmojiBean.fromCodePoint(0x1f50f),
//            EmojiBean.fromCodePoint(0x1f510),
//            EmojiBean.fromCodePoint(0x1f511),
//            EmojiBean.fromCodePoint(0x1f50e),
//            EmojiBean.fromCodePoint(0x1f4a1),
//            EmojiBean.fromCodePoint(0x1f526),
//            EmojiBean.fromCodePoint(0x1f506),
//            EmojiBean.fromCodePoint(0x1f505),
//            EmojiBean.fromCodePoint(0x1f50c),
//            EmojiBean.fromCodePoint(0x1f50b),
            "emoji_0x1f50d.png," + EmoticonBean.fromCodePoint(0x1f50d),
//            EmojiBean.fromCodePoint(0x1f6c1),
//            EmojiBean.fromCodePoint(0x1f6c0),
//            EmojiBean.fromCodePoint(0x1f6bf),
//            EmojiBean.fromCodePoint(0x1f6bd),
//            EmojiBean.fromCodePoint(0x1f527),
//            EmojiBean.fromCodePoint(0x1f529),
//            EmojiBean.fromCodePoint(0x1f528),
//            EmojiBean.fromCodePoint(0x1f6aa),
//            EmojiBean.fromCodePoint(0x1f6ac),
            "emoji_0x1f4a3.png," + EmoticonBean.fromCodePoint(0x1f4a3),
//            EmojiBean.fromCodePoint(0x1f52b),
//            EmojiBean.fromCodePoint(0x1f52a),
//            EmojiBean.fromCodePoint(0x1f48a),
//            EmojiBean.fromCodePoint(0x1f489),
//            EmojiBean.fromCodePoint(0x1f4b0),
//            EmojiBean.fromCodePoint(0x1f4b4),
//            EmojiBean.fromCodePoint(0x1f4b5),
//            EmojiBean.fromCodePoint(0x1f4b7),
//            EmojiBean.fromCodePoint(0x1f4b6),
//            EmojiBean.fromCodePoint(0x1f4b3),
//            EmojiBean.fromCodePoint(0x1f4b8),
//            EmojiBean.fromCodePoint(0x1f4f2),
//            EmojiBean.fromCodePoint(0x1f4e7),
//            EmojiBean.fromCodePoint(0x1f4e5),
//            EmojiBean.fromCodePoint(0x1f4e4),
//            EmojiBean.fromChar((char) 0x2709),
//            EmojiBean.fromCodePoint(0x1f4e9),
//            EmojiBean.fromCodePoint(0x1f4e8),
//            EmojiBean.fromCodePoint(0x1f4ef),
//            EmojiBean.fromCodePoint(0x1f4eb),
//            EmojiBean.fromCodePoint(0x1f4ea),
//            EmojiBean.fromCodePoint(0x1f4ec),
//            EmojiBean.fromCodePoint(0x1f4ed),
//            EmojiBean.fromCodePoint(0x1f4ee),
//            EmojiBean.fromCodePoint(0x1f4e6),
//            EmojiBean.fromCodePoint(0x1f4dd),
//            EmojiBean.fromCodePoint(0x1f4c4),
//            EmojiBean.fromCodePoint(0x1f4c3),
//            EmojiBean.fromCodePoint(0x1f4d1),
//            EmojiBean.fromCodePoint(0x1f4ca),
//            EmojiBean.fromCodePoint(0x1f4c8),
//            EmojiBean.fromCodePoint(0x1f4c9),
//            EmojiBean.fromCodePoint(0x1f4dc),
//            EmojiBean.fromCodePoint(0x1f4cb),
//            EmojiBean.fromCodePoint(0x1f4c5),
//            EmojiBean.fromCodePoint(0x1f4c6),
//            EmojiBean.fromCodePoint(0x1f4c7),
//            EmojiBean.fromCodePoint(0x1f4c1),
//            EmojiBean.fromCodePoint(0x1f4c2),
//            EmojiBean.fromChar((char) 0x2702),
//            EmojiBean.fromCodePoint(0x1f4cc),
//            EmojiBean.fromCodePoint(0x1f4ce),
//            EmojiBean.fromChar((char) 0x2712),
//            EmojiBean.fromChar((char) 0x270f),
//            EmojiBean.fromCodePoint(0x1f4cf),
//            EmojiBean.fromCodePoint(0x1f4d0),
//            EmojiBean.fromCodePoint(0x1f4d5),
//            EmojiBean.fromCodePoint(0x1f4d7),
//            EmojiBean.fromCodePoint(0x1f4d8),
//            EmojiBean.fromCodePoint(0x1f4d9),
//            EmojiBean.fromCodePoint(0x1f4d3),
//            EmojiBean.fromCodePoint(0x1f4d4),
//            EmojiBean.fromCodePoint(0x1f4d2),
//            EmojiBean.fromCodePoint(0x1f4da),
//            EmojiBean.fromCodePoint(0x1f4d6),
//            EmojiBean.fromCodePoint(0x1f516),
//            EmojiBean.fromCodePoint(0x1f4db),
//            EmojiBean.fromCodePoint(0x1f52c),
//            EmojiBean.fromCodePoint(0x1f52d),
//            EmojiBean.fromCodePoint(0x1f4f0),
//            EmojiBean.fromCodePoint(0x1f3a8),
//            EmojiBean.fromCodePoint(0x1f3ac),
//            EmojiBean.fromCodePoint(0x1f3a4),
//            EmojiBean.fromCodePoint(0x1f3a7),
//            EmojiBean.fromCodePoint(0x1f3bc),
//            EmojiBean.fromCodePoint(0x1f3b5),
//            EmojiBean.fromCodePoint(0x1f3b6),
//            EmojiBean.fromCodePoint(0x1f3b9),
//            EmojiBean.fromCodePoint(0x1f3bb),
//            EmojiBean.fromCodePoint(0x1f3ba),
//            EmojiBean.fromCodePoint(0x1f3b7),
//            EmojiBean.fromCodePoint(0x1f3b8),
//            EmojiBean.fromCodePoint(0x1f47e),
//            EmojiBean.fromCodePoint(0x1f3ae),
//            EmojiBean.fromCodePoint(0x1f0cf),
//            EmojiBean.fromCodePoint(0x1f3b4),
//            EmojiBean.fromCodePoint(0x1f004),
//            EmojiBean.fromCodePoint(0x1f3b2),
//            EmojiBean.fromCodePoint(0x1f3af),
//            EmojiBean.fromCodePoint(0x1f3c8),
//            EmojiBean.fromCodePoint(0x1f3c0),
            "emoji_0x26bd" + ".png," + EmoticonBean.fromChar((char) 0x26bd),
//            EmojiBean.fromChar((char) 0x26be),
//            EmojiBean.fromCodePoint(0x1f3be),
//            EmojiBean.fromCodePoint(0x1f3b1),
//            EmojiBean.fromCodePoint(0x1f3c9),
//            EmojiBean.fromCodePoint(0x1f3b3),
//            EmojiBean.fromChar((char) 0x26f3),
//            EmojiBean.fromCodePoint(0x1f6b5),
//            EmojiBean.fromCodePoint(0x1f6b4),
//            EmojiBean.fromCodePoint(0x1f3c1),
//            EmojiBean.fromCodePoint(0x1f3c7),
//            EmojiBean.fromCodePoint(0x1f3c6),
//            EmojiBean.fromCodePoint(0x1f3bf),
//            EmojiBean.fromCodePoint(0x1f3c2),
//            EmojiBean.fromCodePoint(0x1f3ca),
//            EmojiBean.fromCodePoint(0x1f3c4),
//            EmojiBean.fromCodePoint(0x1f3a3),
            "emoji_0x2615" + ".png," + EmoticonBean.fromChar((char) 0x2615),
//            EmojiBean.fromCodePoint(0x1f375),
//            EmojiBean.fromCodePoint(0x1f376),
//            EmojiBean.fromCodePoint(0x1f37c),
            "emoji_0x1f37a" + ".png," + EmoticonBean.fromCodePoint(0x1f37a),
//            EmojiBean.fromCodePoint(0x1f37b),
//            EmojiBean.fromCodePoint(0x1f378),
//            EmojiBean.fromCodePoint(0x1f379),
//            EmojiBean.fromCodePoint(0x1f377),
//            EmojiBean.fromCodePoint(0x1f374),
//            EmojiBean.fromCodePoint(0x1f355),
//            EmojiBean.fromCodePoint(0x1f354),
//            EmojiBean.fromCodePoint(0x1f35f),
//            EmojiBean.fromCodePoint(0x1f357),
//            EmojiBean.fromCodePoint(0x1f356),
//            EmojiBean.fromCodePoint(0x1f35d),
//            EmojiBean.fromCodePoint(0x1f35b),
//            EmojiBean.fromCodePoint(0x1f364),
//            EmojiBean.fromCodePoint(0x1f371),
//            EmojiBean.fromCodePoint(0x1f363),
//            EmojiBean.fromCodePoint(0x1f365),
//            EmojiBean.fromCodePoint(0x1f359),
//            EmojiBean.fromCodePoint(0x1f358),
//            EmojiBean.fromCodePoint(0x1f35a),
//            EmojiBean.fromCodePoint(0x1f35c),
//            EmojiBean.fromCodePoint(0x1f372),
//            EmojiBean.fromCodePoint(0x1f362),
//            EmojiBean.fromCodePoint(0x1f361),
//            EmojiBean.fromCodePoint(0x1f373),
//            EmojiBean.fromCodePoint(0x1f35e),
//            EmojiBean.fromCodePoint(0x1f369),
//            EmojiBean.fromCodePoint(0x1f36e),
//            EmojiBean.fromCodePoint(0x1f366),
//            EmojiBean.fromCodePoint(0x1f368),
//            EmojiBean.fromCodePoint(0x1f367),
            "emoji_0x1f382" + ".png," + EmoticonBean.fromCodePoint(0x1f382),
//            EmojiBean.fromCodePoint(0x1f370),
//            EmojiBean.fromCodePoint(0x1f36a),
//            EmojiBean.fromCodePoint(0x1f36b),
//            EmojiBean.fromCodePoint(0x1f36c),
//            EmojiBean.fromCodePoint(0x1f36d),
//            EmojiBean.fromCodePoint(0x1f36f),
//            EmojiBean.fromCodePoint(0x1f34e),
//            EmojiBean.fromCodePoint(0x1f34f),
//            EmojiBean.fromCodePoint(0x1f34a),
//            EmojiBean.fromCodePoint(0x1f34b),
//            EmojiBean.fromCodePoint(0x1f352),
//            EmojiBean.fromCodePoint(0x1f347),
//            EmojiBean.fromCodePoint(0x1f349),
//            EmojiBean.fromCodePoint(0x1f353),
//            EmojiBean.fromCodePoint(0x1f351),
//            EmojiBean.fromCodePoint(0x1f348),
//            EmojiBean.fromCodePoint(0x1f34c),
//            EmojiBean.fromCodePoint(0x1f350),
//            EmojiBean.fromCodePoint(0x1f34d),
//            EmojiBean.fromCodePoint(0x1f360),
//            EmojiBean.fromCodePoint(0x1f346),
//            EmojiBean.fromCodePoint(0x1f345),
//            EmojiBean.fromCodePoint(0x1f33d),


            // PLACES
            "emoji_0x1f3e0.png," + EmoticonBean.fromCodePoint(0x1f3e0),
//            EmojiBean.fromCodePoint(0x1f3e1),
//            EmojiBean.fromCodePoint(0x1f3eb),
//            EmojiBean.fromCodePoint(0x1f3e2),
//            EmojiBean.fromCodePoint(0x1f3e3),
//            EmojiBean.fromCodePoint(0x1f3e5),
//            EmojiBean.fromCodePoint(0x1f3e6),
//            EmojiBean.fromCodePoint(0x1f3ea),
//            EmojiBean.fromCodePoint(0x1f3e9),
//            EmojiBean.fromCodePoint(0x1f3e8),
//            EmojiBean.fromCodePoint(0x1f492),
//            EmojiBean.fromChar((char) 0x26ea),
//            EmojiBean.fromCodePoint(0x1f3ec),
//            EmojiBean.fromCodePoint(0x1f3e4),
//            EmojiBean.fromCodePoint(0x1f307),
//            EmojiBean.fromCodePoint(0x1f306),
//            EmojiBean.fromCodePoint(0x1f3ef),
//            EmojiBean.fromCodePoint(0x1f3f0),
//            EmojiBean.fromChar((char) 0x26fa),
//            EmojiBean.fromCodePoint(0x1f3ed),
//            EmojiBean.fromCodePoint(0x1f5fc),
//            EmojiBean.fromCodePoint(0x1f5fe),
//            EmojiBean.fromCodePoint(0x1f5fb),
//            EmojiBean.fromCodePoint(0x1f304),
//            EmojiBean.fromCodePoint(0x1f305),
//            EmojiBean.fromCodePoint(0x1f303),
//            EmojiBean.fromCodePoint(0x1f5fd),
//            EmojiBean.fromCodePoint(0x1f309),
//            EmojiBean.fromCodePoint(0x1f3a0),
//            EmojiBean.fromCodePoint(0x1f3a1),
//            EmojiBean.fromChar((char) 0x26f2),
//            EmojiBean.fromCodePoint(0x1f3a2),
//            EmojiBean.fromCodePoint(0x1f6a2),
//            EmojiBean.fromChar((char) 0x26f5),
//            EmojiBean.fromCodePoint(0x1f6a4),
//            EmojiBean.fromCodePoint(0x1f6a3),
//            EmojiBean.fromChar((char) 0x2693),
//            EmojiBean.fromCodePoint(0x1f680),
//            EmojiBean.fromChar((char) 0x2708),
//            EmojiBean.fromCodePoint(0x1f4ba),
//            EmojiBean.fromCodePoint(0x1f681),
//            EmojiBean.fromCodePoint(0x1f682),
//            EmojiBean.fromCodePoint(0x1f68a),
//            EmojiBean.fromCodePoint(0x1f689),
//            EmojiBean.fromCodePoint(0x1f69e),
//            EmojiBean.fromCodePoint(0x1f686),
//            EmojiBean.fromCodePoint(0x1f684),
//            EmojiBean.fromCodePoint(0x1f685),
//            EmojiBean.fromCodePoint(0x1f688),
//            EmojiBean.fromCodePoint(0x1f687),
//            EmojiBean.fromCodePoint(0x1f69d),
//            EmojiBean.fromCodePoint(0x1f68b),
//            EmojiBean.fromCodePoint(0x1f683),
//            EmojiBean.fromCodePoint(0x1f68e),
//            EmojiBean.fromCodePoint(0x1f68c),
//            EmojiBean.fromCodePoint(0x1f68d),
//            EmojiBean.fromCodePoint(0x1f699),
//            EmojiBean.fromCodePoint(0x1f698),
            "emoji_0x1f697" + ".png," + EmoticonBean.fromCodePoint(0x1f697),
//            EmojiBean.fromCodePoint(0x1f695),
//            EmojiBean.fromCodePoint(0x1f696),
//            EmojiBean.fromCodePoint(0x1f69b),
//            EmojiBean.fromCodePoint(0x1f69a),
//            EmojiBean.fromCodePoint(0x1f6a8),
//            EmojiBean.fromCodePoint(0x1f693),
//            EmojiBean.fromCodePoint(0x1f694),
//            EmojiBean.fromCodePoint(0x1f692),
//            EmojiBean.fromCodePoint(0x1f691),
//            EmojiBean.fromCodePoint(0x1f690),
//            EmojiBean.fromCodePoint(0x1f6b2),
//            EmojiBean.fromCodePoint(0x1f6a1),
//            EmojiBean.fromCodePoint(0x1f69f),
//            EmojiBean.fromCodePoint(0x1f6a0),
//            EmojiBean.fromCodePoint(0x1f69c),
//            EmojiBean.fromCodePoint(0x1f488),
//            EmojiBean.fromCodePoint(0x1f68f),
//            EmojiBean.fromCodePoint(0x1f3ab),
//            EmojiBean.fromCodePoint(0x1f6a6),
//            EmojiBean.fromCodePoint(0x1f6a5),
//            EmojiBean.fromChar((char) 0x26a0),
//            EmojiBean.fromCodePoint(0x1f6a7),
//            EmojiBean.fromCodePoint(0x1f530),
//            EmojiBean.fromChar((char) 0x26fd),
//            EmojiBean.fromCodePoint(0x1f3ee),
//            EmojiBean.fromCodePoint(0x1f3b0),
//            EmojiBean.fromChar((char) 0x2668),
//            EmojiBean.fromCodePoint(0x1f5ff),
//            EmojiBean.fromCodePoint(0x1f3aa),
//            EmojiBean.fromCodePoint(0x1f3ad),
//            EmojiBean.fromCodePoint(0x1f4cd),
//            EmojiBean.fromCodePoint(0x1f6a9),
//            EmojiBean.fromChars("\ud83c\uddef\ud83c\uddf5"),
//            EmojiBean.fromChars("\ud83c\uddf0\ud83c\uddf7"),
//            EmojiBean.fromChars("\ud83c\udde9\ud83c\uddea"),
//            EmojiBean.fromChars("\ud83c\udde8\ud83c\uddf3"),
//            EmojiBean.fromChars("\ud83c\uddfa\ud83c\uddf8"),
//            EmojiBean.fromChars("\ud83c\uddeb\ud83c\uddf7"),
//            EmojiBean.fromChars("\ud83c\uddea\ud83c\uddf8"),
//            EmojiBean.fromChars("\ud83c\uddee\ud83c\uddf9"),
//            EmojiBean.fromChars("\ud83c\uddf7\ud83c\uddfa"),
//            EmojiBean.fromChars("\ud83c\uddec\ud83c\udde7"),

            // Symbols
//            EmojiBean.fromChars("\u0031\u20e3"),
//            EmojiBean.fromChars("\u0032\u20e3"),
//            EmojiBean.fromChars("\u0033\u20e3"),
//            EmojiBean.fromChars("\u0034\u20e3"),
//            EmojiBean.fromChars("\u0035\u20e3"),
//            EmojiBean.fromChars("\u0036\u20e3"),
//            EmojiBean.fromChars("\u0037\u20e3"),
//            EmojiBean.fromChars("\u0038\u20e3"),
//            EmojiBean.fromChars("\u0039\u20e3"),
//            EmojiBean.fromChars("\u0030\u20e3"),
//            EmojiBean.fromCodePoint(0x1f51f),
//            EmojiBean.fromCodePoint(0x1f522),
//            EmojiBean.fromChars("\u0023\u20e3"),
//            EmojiBean.fromCodePoint(0x1f523),
//            EmojiBean.fromChar((char) 0x2b06),
//            EmojiBean.fromChar((char) 0x2b07),
//            EmojiBean.fromChar((char) 0x2b05),
//            EmojiBean.fromChar((char) 0x27a1),
//            EmojiBean.fromCodePoint(0x1f520),
//            EmojiBean.fromCodePoint(0x1f521),
//            EmojiBean.fromCodePoint(0x1f524),
//            EmojiBean.fromChar((char) 0x2197),
//            EmojiBean.fromChar((char) 0x2196),
//            EmojiBean.fromChar((char) 0x2198),
//            EmojiBean.fromChar((char) 0x2199),
//            EmojiBean.fromChar((char) 0x2194),
//            EmojiBean.fromChar((char) 0x2195),
//            EmojiBean.fromCodePoint(0x1f504),
//            EmojiBean.fromChar((char) 0x25c0),
//            EmojiBean.fromChar((char) 0x25b6),
//            EmojiBean.fromCodePoint(0x1f53c),
//            EmojiBean.fromCodePoint(0x1f53d),
//            EmojiBean.fromChar((char) 0x21a9),
//            EmojiBean.fromChar((char) 0x21aa),
//            EmojiBean.fromChar((char) 0x2139),
//            EmojiBean.fromChar((char) 0x23ea),
//            EmojiBean.fromChar((char) 0x23e9),
//            EmojiBean.fromChar((char) 0x23eb),
//            EmojiBean.fromChar((char) 0x23ec),
//            EmojiBean.fromChar((char) 0x2935),
//            EmojiBean.fromChar((char) 0x2934),
//            EmojiBean.fromCodePoint(0x1f197),
//            EmojiBean.fromCodePoint(0x1f500),
//            EmojiBean.fromCodePoint(0x1f501),
//            EmojiBean.fromCodePoint(0x1f502),
//            EmojiBean.fromCodePoint(0x1f195),
//            EmojiBean.fromCodePoint(0x1f199),
//            EmojiBean.fromCodePoint(0x1f192),
//            EmojiBean.fromCodePoint(0x1f193),
//            EmojiBean.fromCodePoint(0x1f196),
//            EmojiBean.fromCodePoint(0x1f4f6),
//            EmojiBean.fromCodePoint(0x1f3a6),
//            EmojiBean.fromCodePoint(0x1f201),
//            EmojiBean.fromCodePoint(0x1f22f),
//            EmojiBean.fromCodePoint(0x1f233),
//            EmojiBean.fromCodePoint(0x1f235),
//            EmojiBean.fromCodePoint(0x1f234),
//            EmojiBean.fromCodePoint(0x1f232),
//            EmojiBean.fromCodePoint(0x1f250),
//            EmojiBean.fromCodePoint(0x1f239),
//            EmojiBean.fromCodePoint(0x1f23a),
//            EmojiBean.fromCodePoint(0x1f236),
//            EmojiBean.fromCodePoint(0x1f21a),
//            EmojiBean.fromCodePoint(0x1f6bb),
//            EmojiBean.fromCodePoint(0x1f6b9),
//            EmojiBean.fromCodePoint(0x1f6ba),
//            EmojiBean.fromCodePoint(0x1f6bc),
//            EmojiBean.fromCodePoint(0x1f6be),
//            EmojiBean.fromCodePoint(0x1f6b0),
//            EmojiBean.fromCodePoint(0x1f6ae),
//            EmojiBean.fromCodePoint(0x1f17f),
//            EmojiBean.fromChar((char) 0x267f),
//            EmojiBean.fromCodePoint(0x1f6ad),
//            EmojiBean.fromCodePoint(0x1f237),
//            EmojiBean.fromCodePoint(0x1f238),
//            EmojiBean.fromCodePoint(0x1f202),
//            EmojiBean.fromChar((char) 0x24c2),
//            EmojiBean.fromCodePoint(0x1f6c2),
//            EmojiBean.fromCodePoint(0x1f6c4),
//            EmojiBean.fromCodePoint(0x1f6c5),
//            EmojiBean.fromCodePoint(0x1f6c3),
//            EmojiBean.fromCodePoint(0x1f251),
//            EmojiBean.fromChar((char) 0x3299),
//            EmojiBean.fromChar((char) 0x3297),
//            EmojiBean.fromCodePoint(0x1f191),
//            EmojiBean.fromCodePoint(0x1f198),
//            EmojiBean.fromCodePoint(0x1f194),
//            EmojiBean.fromCodePoint(0x1f6ab),
//            EmojiBean.fromCodePoint(0x1f51e),
//            EmojiBean.fromCodePoint(0x1f4f5),
//            EmojiBean.fromCodePoint(0x1f6af),
//            EmojiBean.fromCodePoint(0x1f6b1),
//            EmojiBean.fromCodePoint(0x1f6b3),
//            EmojiBean.fromCodePoint(0x1f6b7),
//            EmojiBean.fromCodePoint(0x1f6b8),
//            EmojiBean.fromChar((char) 0x26d4),
//            EmojiBean.fromChar((char) 0x2733),
//            EmojiBean.fromChar((char) 0x2747),
//            EmojiBean.fromChar((char) 0x274e),
//            EmojiBean.fromChar((char) 0x2705),
//            EmojiBean.fromChar((char) 0x2734),
//            EmojiBean.fromCodePoint(0x1f49f),
//            EmojiBean.fromCodePoint(0x1f19a),
//            EmojiBean.fromCodePoint(0x1f4f3),
//            EmojiBean.fromCodePoint(0x1f4f4),
//            EmojiBean.fromCodePoint(0x1f170),
//            EmojiBean.fromCodePoint(0x1f171),
//            EmojiBean.fromCodePoint(0x1f18e),
//            EmojiBean.fromCodePoint(0x1f17e),
//            EmojiBean.fromCodePoint(0x1f4a0),
//            EmojiBean.fromChar((char) 0x27bf),
//            EmojiBean.fromChar((char) 0x267b),
//            EmojiBean.fromChar((char) 0x2648),
//            EmojiBean.fromChar((char) 0x2649),
//            EmojiBean.fromChar((char) 0x264a),
//            EmojiBean.fromChar((char) 0x264b),
//            EmojiBean.fromChar((char) 0x264c),
//            EmojiBean.fromChar((char) 0x264d),
//            EmojiBean.fromChar((char) 0x264e),
//            EmojiBean.fromChar((char) 0x264f),
//            EmojiBean.fromChar((char) 0x2650),
//            EmojiBean.fromChar((char) 0x2651),
//            EmojiBean.fromChar((char) 0x2652),
//            EmojiBean.fromChar((char) 0x2653),
//            EmojiBean.fromChar((char) 0x26ce),
//            EmojiBean.fromCodePoint(0x1f52f),
//            EmojiBean.fromCodePoint(0x1f3e7),
//            EmojiBean.fromCodePoint(0x1f4b9),
//            EmojiBean.fromCodePoint(0x1f4b2),
//            EmojiBean.fromCodePoint(0x1f4b1),
//            Emoji.fromChar((char)0x00a9),
//            Emoji.fromChar((char)0x00ae),
//            EmojiBean.fromChar((char) 0xe24e),
//            EmojiBean.fromChar((char) 0xe24f),

//            EmojiBean.fromChar((char) 0x2122),
//            EmojiBean.fromChar((char) 0x274c),
//            EmojiBean.fromChar((char) 0x203c),
//            EmojiBean.fromChar((char) 0x2049),
//            EmojiBean.fromChar((char) 0x2757),
//            EmojiBean.fromChar((char) 0x2753),
//            EmojiBean.fromChar((char) 0x2755),
//            EmojiBean.fromChar((char) 0x2754),
//            EmojiBean.fromChar((char) 0x2b55),
//            EmojiBean.fromCodePoint(0x1f51d),
//            EmojiBean.fromCodePoint(0x1f51a),
//            EmojiBean.fromCodePoint(0x1f519),
//            EmojiBean.fromCodePoint(0x1f51b),
//            EmojiBean.fromCodePoint(0x1f51c),
//            EmojiBean.fromCodePoint(0x1f503),
//            EmojiBean.fromCodePoint(0x1f55b),
//            EmojiBean.fromCodePoint(0x1f567),
//            EmojiBean.fromCodePoint(0x1f550),
//            EmojiBean.fromCodePoint(0x1f55c),
//            EmojiBean.fromCodePoint(0x1f551),
//            EmojiBean.fromCodePoint(0x1f55d),
//            EmojiBean.fromCodePoint(0x1f552),
//            EmojiBean.fromCodePoint(0x1f55e),
//            EmojiBean.fromCodePoint(0x1f553),
//            EmojiBean.fromCodePoint(0x1f55f),
//            EmojiBean.fromCodePoint(0x1f554),
//            EmojiBean.fromCodePoint(0x1f560),
//            EmojiBean.fromCodePoint(0x1f555),
//            EmojiBean.fromCodePoint(0x1f556),
//            EmojiBean.fromCodePoint(0x1f557),
//            EmojiBean.fromCodePoint(0x1f558),
            "emoji_0x1f559" + ".png," + EmoticonBean.fromCodePoint(0x1f559),
//            EmojiBean.fromCodePoint(0x1f55a),
//            EmojiBean.fromCodePoint(0x1f561),
//            EmojiBean.fromCodePoint(0x1f562),
//            EmojiBean.fromCodePoint(0x1f563),
//            EmojiBean.fromCodePoint(0x1f564),
//            EmojiBean.fromCodePoint(0x1f565),
//            EmojiBean.fromCodePoint(0x1f566),
//            EmojiBean.fromChar((char) 0x2716),
//            EmojiBean.fromChar((char) 0x2795),
//            EmojiBean.fromChar((char) 0x2796),
//            EmojiBean.fromChar((char) 0x2797),
//            EmojiBean.fromChar((char) 0x2660),
//            EmojiBean.fromChar((char) 0x2665),
//            EmojiBean.fromChar((char) 0x2663),
//            EmojiBean.fromChar((char) 0x2666),
//            EmojiBean.fromCodePoint(0x1f4ae),
//            EmojiBean.fromCodePoint(0x1f4af),
//            EmojiBean.fromChar((char) 0x2714),
//            EmojiBean.fromChar((char) 0x2611),
//            EmojiBean.fromCodePoint(0x1f518),
//            EmojiBean.fromCodePoint(0x1f517),
//            EmojiBean.fromChar((char) 0x27b0),
//            EmojiBean.fromChar((char) 0x3030),
//            EmojiBean.fromChar((char) 0x303d),
//            EmojiBean.fromCodePoint(0x1f531),
//            EmojiBean.fromChar((char) 0x25fc),
//            EmojiBean.fromChar((char) 0x25fb),
//            EmojiBean.fromChar((char) 0x25fe),
//            EmojiBean.fromChar((char) 0x25fd),
//            EmojiBean.fromChar((char) 0x25aa),
//            EmojiBean.fromChar((char) 0x25ab),
//            EmojiBean.fromCodePoint(0x1f53a),
//            EmojiBean.fromCodePoint(0x1f532),
//            EmojiBean.fromCodePoint(0x1f533),
//            EmojiBean.fromChar((char) 0x26ab),
//            EmojiBean.fromChar((char) 0x26aa),
//            EmojiBean.fromCodePoint(0x1f534),
//            EmojiBean.fromCodePoint(0x1f535),
//            EmojiBean.fromCodePoint(0x1f53b),
//            EmojiBean.fromChar((char) 0x2b1c),
//            EmojiBean.fromChar((char) 0x2b1b),
//            EmojiBean.fromCodePoint(0x1f536),
//            EmojiBean.fromCodePoint(0x1f537),
//            EmojiBean.fromCodePoint(0x1f538),
//            EmojiBean.fromCodePoint(0x1f539),
    };
}